# 配置服务器的端口，通常设置为8888:
server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    # 从文件读取配置时，Config Server激活的profile必须设定为native:
    active: native
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      server:
        native:
          # 设置配置文件的搜索路径:
          search-locations: classpath:/config
